apiVersion: v1
kind: Service
metadata:
  name: splunk-student921-standalone-0
  namespace: splunk
spec:
  ports:
  - name: http-splunk 
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: splunk-student921-standalone
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: standalone
    app.kubernetes.io/part-of: splunk-student921-standalone
    statefulset.kubernetes.io/pod-name: splunk-student921-standalone-0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

